{
 "title": "Ethereum",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "EVM Contract Instantiation Latency p99 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_evm_contract_instantiation_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVM Contract Instantiation Latency p50 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_evm_contract_instantiation_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVM Service Instantiation Latency p99 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_evm_service_instantiation_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EVM Service Instantiation Latency p50 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_evm_service_instantiation_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}