{
 "title": "Execution",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Execution Latency p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_block_execution_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Execution Latency p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_block_execution_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operation Execution Latency p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_operation_execution_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operation Execution Latency p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_operation_execution_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Execution Latency p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_message_execution_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Execution Latency p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_message_execution_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytecode decompression latency p99 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_bytecode_decompression_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytecode decompression latency p50 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_bytecode_decompression_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "State hash computation latency p99 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_state_hash_computation_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "State hash computation latency p50 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_state_hash_computation_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Chains opened per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(linera_open_chain_count[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks executed per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(linera_num_blocks_executed[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks added to chains per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(linera_num_blocks[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(linera_transaction_count[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification channel full per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(linera_notification_channel_full[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross chain message channel full per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(linera_cross_chain_message_channel_full[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates signed per second per validator (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(linera_certificates_signed[2m])) by (validator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Value cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "((\n  sum(rate(linera_value_cache_hit[2m])) by (key_type, value_type)\n)\n/\n(\n  sum(rate(linera_value_cache_hit[2m])) by (key_type, value_type)\n  +\n  sum(rate(linera_value_cache_miss[2m])) by (key_type, value_type)\n)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rounds in certificate p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_num_rounds_in_certificate_bucket[2m])) by (le, certificate_value, round_type, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rounds in certificate p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_num_rounds_in_certificate_bucket[2m])) by (le, certificate_value, round_type, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of inboxes p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_num_inboxes_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of inboxes p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_num_inboxes_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of outboxes p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_num_outboxes_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of outboxes p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_num_outboxes_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inbox size p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_inbox_size_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inbox size p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_inbox_size_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbox size p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_outbox_size_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbox size p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_outbox_size_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Removed bundles p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_removed_bundles_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Removed bundles p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_removed_bundles_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rounds in block proposal p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_num_rounds_in_block_proposal_bucket[2m])) by (le, round_type, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rounds in block proposal p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_num_rounds_in_block_proposal_bucket[2m])) by (le, round_type, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Certificates signed per validator",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum(linera_certificates_signed) by (validator_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Wasm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wasm Contract Instantiation Latency p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_contract_instantiation_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm Contract Instantiation Latency p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_contract_instantiation_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm Service Instantiation Latency p99 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_service_instantiation_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm Service Instantiation Latency p50 ms (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_service_instantiation_latency_bucket[2m])) by (le, validator))",
       "legendFormat": "{{pod}} - {{le}}"
      }
     ]
    },
    {
     "title": "Wasm fuel used per block p99 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_fuel_used_per_block_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm fuel used per block p50 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_fuel_used_per_block_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm num reads per block p99 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_num_reads_per_block_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm num reads per block p50 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_num_reads_per_block_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm bytes read per block p99 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_bytes_read_per_block_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm bytes read per block p50 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_bytes_read_per_block_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm bytes written per block p99 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(linera_wasm_bytes_written_per_block_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wasm bytes written per block p50 (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(linera_wasm_bytes_written_per_block_bucket[2m])) by (le, validator))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}