{
 "title": "General",
 "tags": [ "linera" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy requests per second (averaged for the past 2 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(linera_proxy_request_count[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Error rate (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(\n    (\n        sum(rate(linera_proxy_request_error[2m])) by (validator)\n    ) / (\n        (\n            (\n                sum(rate(linera_proxy_request_success[2m])) by (validator)\n            ) + (\n                sum(rate(linera_proxy_request_error[2m])) by (validator)\n            )\n        )\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy p99 latency ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, validator) (rate(linera_proxy_request_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy p90 latency ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(linera_proxy_request_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy p50 latency ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_proxy_request_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Server requests per second (averaged for the past 2 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(linera_server_request_count[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Error rate (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "(\n    (\n        sum(rate(linera_server_request_error[2m])) by (validator)\n    ) / (\n        (\n            (\n                sum(rate(linera_server_request_success[2m])) by (validator)\n            ) + (\n                sum(rate(linera_server_request_error[2m])) by (validator)\n            )\n        ) or vector(1)\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p99 latency ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_server_request_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p90 latency ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(linera_server_request_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p50 latency ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_server_request_latency_bucket[2m])) by (le, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p99 latency per request type ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(linera_server_request_latency_per_request_type_bucket[2m])) by (le, method_name, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p90 latency per request type ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(linera_server_request_latency_per_request_type_bucket[2m])) by (le, method_name, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server p50 latency per request type ms (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(linera_server_request_latency_per_request_type_bucket[2m])) by (le, method_name, validator))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Network bytes TX/RX total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[60s])) by (validator, container) + sum(rate(container_network_transmit_bytes_total[60s])) by (validator)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"linera.*\"}) by (validator, container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"linera.*\"}) by (validator)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"linera.*\"}[60s])) by (validator, container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scylla Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(validator) (container_memory_usage_bytes{container=\"scylla\"})",
     "legendFormat": "{{validator}}"
    }
   ]
  }
 ]
}