{
 "title": "Storage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load view latency p99 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, validator) (rate(linera_load_view_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load view latency p50 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, validator) (rate(linera_load_view_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load chain latency p99 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, validator) (rate(linera_load_chain_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load chain latency p50 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, validator) (rate(linera_load_chain_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load contract latency p99 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, validator) (rate(linera_load_contract_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load contract latency p50 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, validator) (rate(linera_load_contract_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load service latency p99 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, validator) (rate(linera_load_service_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load service latency p50 (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, validator) (rate(linera_load_service_latency_bucket[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Contains blobs per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(linera_contains_blobs[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contains blob state per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(linera_contains_blob_state[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write event per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(linera_write_event[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read event per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(linera_read_event[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read certificates per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(linera_read_certificates[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read certificate per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(linera_read_certificate[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read blob states per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(linera_read_blob_states[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read blob state per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(linera_read_blob_state[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write blob per second (averaged for the last 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(linera_write_blob[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read blob per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(linera_read_blob[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write certificate per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(rate(linera_write_certificate[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read hashed confirmed block per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum(rate(linera_read_hashed_confirmed_block[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contains Blob per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(linera_contains_blob[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contains certificate per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(linera_contains_certificate[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}