{
 "title": "Views",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Save view per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(linera_save_view[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load view per second (averaged for the past 2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(linera_load_view[2m])) by (validator)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit ratio (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(linera_num_cache_success[2m])) by (validator) / (sum(rate(linera_num_cache_success[2m])) by (validator) + sum(rate(linera_num_cache_fault[2m])) by (validator))) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}